const Mock = require('mockjs');
const appName = process.env.VUE_APP_NAME;

export const mockCurrent = Mock.mock(RegExp(`/${appName}/_baseAPI/api/user/current`), 'get', {
  data: { name: 'Admin', erp: 'admin' },
  success: true,
  msg: '',
});

export const mockTotal = Mock.mock(RegExp(`/${appName}/_baseAPI/api/common/total`), 'get', {
  data: {
    appCount: 10,
    appWorkflowCount: 12,
    appVersionCount: 12,
    productCount: 6,
    productWorkflowCount: 10,
    productVersionCount: 9,
  },
  success: true,
  msg: '',
});

export const mockApps = Mock.mock(RegExp(`/${appName}/_baseAPI/api/apps`), 'get', {
  data: {
    count: 10,
    rows: [
      {
        id: 10,
        createdAt: '2023-01-10 16:06:50',
        creator: 'admin',
        updatedAt: '2023-01-10 16:07:21',
        modifier: 'admin',
        deletedAt: null,
        _options: { member: true, upgrade: true },
        name: 'uj-platform-marketing',
        description: 'uj-platform-marketing',
        identifier: 'uj-platform-marketing',
        envCode: 20,
        type: 20,
        status: 30,
        version: '0.0.1',
        assetMode: 10,
        canUpgrade: true,
        envCodeView: '预发环境',
        statusView: '已上线',
        typeView: '子应用',
        assetModeView: '基础配置',
      },
      {
        id: 9,
        createdAt: '2023-01-10 16:05:43',
        creator: 'admin',
        updatedAt: '2023-01-10 16:07:23',
        modifier: 'admin',
        deletedAt: null,
        _options: { member: true },
        name: 'uj-platform-portal',
        description: 'uj-platform-portal',
        identifier: 'uj-platform-portal',
        envCode: 20,
        type: 10,
        status: 30,
        version: '0.0.1',
        assetMode: 10,
        canUpgrade: false,
        envCodeView: '预发环境',
        statusView: '已上线',
        typeView: '主应用',
        assetModeView: '基础配置',
      },
      {
        id: 8,
        createdAt: '2022-12-29 12:11:03',
        creator: 'fuyanan5',
        updatedAt: '2022-12-29 12:42:30',
        modifier: 'fuyanan5',
        deletedAt: null,
        _options: { member: true },
        name: 'fm-cli-template-test',
        description: '前端共建测试项目',
        identifier: 'fm-cli-template-test',
        envCode: 20,
        type: 20,
        status: 10,
        version: null,
        assetMode: 10,
        canUpgrade: true,
        envCodeView: '预发环境',
        statusView: '草稿',
        typeView: '子应用',
        assetModeView: '基础配置',
      },
      {
        id: 7,
        createdAt: '2022-12-27 17:15:35',
        creator: 'admin',
        updatedAt: '2022-12-27 20:04:40',
        modifier: 'admin',
        deletedAt: null,
        _options: { member: true },
        name: 'uj-marketing-pre',
        description: 'uj-marketing-pre',
        identifier: 'marketing',
        envCode: 20,
        type: 20,
        status: 30,
        version: '0.0.2',
        assetMode: 10,
        canUpgrade: false,
        envCodeView: '预发环境',
        statusView: '已上线',
        typeView: '子应用',
        assetModeView: '基础配置',
      },
      {
        id: 6,
        createdAt: '2022-12-27 17:15:09',
        creator: 'admin',
        updatedAt: '2022-12-27 17:16:41',
        modifier: 'admin',
        deletedAt: null,
        _options: { member: true },
        name: 'uj-bi-pre',
        description: 'uj-bi-pre',
        identifier: 'bi',
        envCode: 20,
        type: 20,
        status: 30,
        version: '0.0.1',
        assetMode: 10,
        canUpgrade: false,
        envCodeView: '预发环境',
        statusView: '已上线',
        typeView: '子应用',
        assetModeView: '基础配置',
      },
      {
        id: 5,
        createdAt: '2022-12-27 17:14:27',
        creator: 'admin',
        updatedAt: '2022-12-27 20:04:42',
        modifier: 'admin',
        deletedAt: null,
        _options: { member: true },
        name: 'uj-portal-pre',
        description: 'uj-portal-pre',
        identifier: 'portal',
        envCode: 20,
        type: 10,
        status: 30,
        version: '0.0.2',
        assetMode: 10,
        canUpgrade: false,
        envCodeView: '预发环境',
        statusView: '已上线',
        typeView: '主应用',
        assetModeView: '基础配置',
      },
      {
        id: 4,
        createdAt: '2022-12-27 17:13:34',
        creator: 'admin',
        updatedAt: '2022-12-27 17:16:44',
        modifier: 'admin',
        deletedAt: null,
        _options: { member: true },
        name: 'uj-workbench-pre',
        description: 'uj-workbench-pre',
        identifier: 'workbench',
        envCode: 20,
        type: 20,
        status: 30,
        version: '0.0.1',
        assetMode: 10,
        canUpgrade: false,
        envCodeView: '预发环境',
        statusView: '已上线',
        typeView: '子应用',
        assetModeView: '基础配置',
      },
      {
        id: 3,
        createdAt: '2022-12-27 17:13:01',
        creator: 'admin',
        updatedAt: '2022-12-27 17:16:46',
        modifier: 'admin',
        deletedAt: null,
        _options: { member: true },
        name: 'uj-marketing-fin-pre',
        description: 'uj-marketing-fin-pre',
        identifier: 'marketing-fin',
        envCode: 20,
        type: 20,
        status: 30,
        version: '0.0.1',
        assetMode: 20,
        canUpgrade: false,
        envCodeView: '预发环境',
        statusView: '已上线',
        typeView: '子应用',
        assetModeView: '自定义配置',
      },
      {
        id: 2,
        createdAt: '2022-12-27 17:11:29',
        creator: 'admin',
        updatedAt: '2022-12-27 17:16:48',
        modifier: 'admin',
        deletedAt: null,
        _options: { member: true },
        name: 'uj-touch-pre',
        description: 'uj-touch-pre',
        identifier: 'uj-touch',
        envCode: 20,
        type: 20,
        status: 30,
        version: '0.0.1',
        assetMode: 10,
        canUpgrade: false,
        envCodeView: '预发环境',
        statusView: '已上线',
        typeView: '子应用',
        assetModeView: '基础配置',
      },
      {
        id: 1,
        createdAt: '2022-12-27 17:10:48',
        creator: 'admin',
        updatedAt: '2022-12-27 20:16:12',
        modifier: 'admin',
        deletedAt: null,
        _options: { member: true },
        name: 'uj-man-pre',
        description: 'uj-man-pre',
        identifier: 'uj-man',
        envCode: 20,
        type: 20,
        status: 30,
        version: '0.0.2',
        assetMode: 10,
        canUpgrade: false,
        envCodeView: '预发环境',
        statusView: '已上线',
        typeView: '子应用',
        assetModeView: '基础配置',
      },
    ],
    pages: 1,
    pageSize: 10,
    pageNum: 1,
  },
  success: true,
  msg: '',
});

export const mockAppRole = Mock.mock(RegExp(`/${appName}/_baseAPI/api/app/[0-9]+/current`), 'get', {
  data: { role: 10 },
  success: true,
  msg: '',
});

export const mockAppMembers = Mock.mock(
  RegExp(`/${appName}/_baseAPI/api/app/[0-9]+/members`),
  'get',
  {
    data: {
      count: 1,
      rows: [
        {
          id: 10,
          createdAt: '2023-01-10 16:06:50',
          creator: 'admin',
          updatedAt: '2023-01-10 16:06:50',
          modifier: 'admin',
          deletedAt: null,
          appId: 10,
          role: 10,
          name: 'admin',
          account: 'admin',
          app_id: 10,
          _options: { edit: true, delete: true },
          roleView: '管理员',
        },
      ],
      pages: 1,
      pageSize: 10,
      pageNum: 1,
    },
    success: true,
    msg: '',
  },
);

export const mockAppMemberCreate = Mock.mock(
  RegExp(`/${appName}/_baseAPI/api/app/[0-9]+/member`),
  'post',
  { data: { id: 1 }, success: true, msg: '' },
);

export const mockAppMemberUpdate = Mock.mock(
  RegExp(`/${appName}/_baseAPI/api/app/[0-9]+/member/[0-9]+`),
  'put',
  { data: { id: 1 }, success: true, msg: '' },
);

export const mockAppMemberDelete = Mock.mock(
  RegExp(`/${appName}/_baseAPI/api/app/[0-9]+/member/[0-9]+`),
  'delete',
  { data: { id: 1 }, success: true, msg: '' },
);
